In [17]:
from scipy.sparse import csr_matrix, kron, linalg
import numpy as np

In [18]:
identity_matrix = csr_matrix(
    [
        [1.0, 0.0],
        [0.0, 1.0]
    ],
)

pauli_x = csr_matrix(
    [
        [0.0, 1.0], 
        [1.0, 0.0]
    ]
)

pauli_y = csr_matrix(
    [
        [0.0, -1.0j],
        [1.0j, 0.0]
    ]
)

pauli_z = csr_matrix(
    [
        [1.0, 0.0],
        [0.0, -1.0]
    ]
)

raising_op = (1 / 2) * (pauli_x + 1.0j* pauli_y)
lowering_op = (1 / 2) * (pauli_x - 1.0j * pauli_y)

In [31]:
def jordan_wigner(n_modes, index):
    cop_matrix = 1.0
    for _ in range(index):
        cop_matrix = kron(cop_matrix, -pauli_z, format="csr")
    cop_matrix = kron(cop_matrix, lowering_op, format="csr")
    for _ in range(index + 1, n_modes):
        cop_matrix = kron(cop_matrix, identity_matrix, format="csr")
    return cop_matrix

In [35]:
n_site = 4
ham = jordan_wigner(n_site, 0)@jordan_wigner(n_site, 1) + jordan_wigner(n_site, 1)@jordan_wigner(n_site, 0)
type(ham)

scipy.sparse._csr.csr_matrix

In [36]:
linalg.eigsh(ham)

(array([0., 0., 0., 0., 0., 0.]),
 array([[ 0.06461682+0.28240671j,  0.03965597+0.01227377j,
          0.22040665+0.26711299j,  0.19433517-0.04083061j,
         -0.11501656+0.14837041j, -0.20784162-0.07744825j],
        [-0.15519164-0.16664214j,  0.01725275+0.06518546j,
         -0.18904791+0.12733524j,  0.07033629-0.19756198j,
          0.17323385-0.01708146j,  0.30345141+0.00843122j],
        [-0.19446236+0.03175746j,  0.30541746+0.13479224j,
          0.36796375-0.24648796j,  0.01534276+0.05534402j,
         -0.13323443-0.10969596j,  0.12147087+0.10295431j],
        [-0.09197795-0.11216579j, -0.3123226 +0.20366351j,
         -0.09450951-0.27556908j,  0.19861769-0.2465395j ,
         -0.04891297+0.0373636j , -0.0701019 -0.18276496j],
        [ 0.09121628+0.29092112j,  0.10770245+0.08642687j,
          0.1596053 +0.07837537j,  0.04808026-0.00807643j,
          0.03601918-0.34052968j,  0.0158075 +0.00972482j],
        [-0.10610081-0.0314387j , -0.2651567 +0.22861851j,
          0.03948

In [39]:
pauli_x@pauli_x.toarray()

array([[1., 0.],
       [0., 1.]])