In [43]:
import numpy as np
from scipy.sparse import csr_matrix, csr_array
from fermion import Fermion
from fermion import SparseFermion


In [37]:
n_modes = 3
f = Fermion(n_modes=n_modes)

com_matrix = np.zeros((n_modes, n_modes))
for i in range(n_modes):
    for j in range(n_modes):
        
        #com_matrix[i, j] = f.cop(i) @ f.cdg(j) + f.cdg(j) @ f.cop(i)
        com_matrix[i, j] = 1
com_matrix
np.all(f.cdg(0) @ f.cop(0) + f.cop(0) @ f.cdg(0) == np.identity(f._dim))
f.cdg(2) @ np.array([0, 0, 0, 0, 0, 0, 0, 1])

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j])

In [16]:
sf = SparseFermion(4)
sf.cop(0) @ sf.cdg(0) + sf.cdg(0) @ sf.cop(0).toarray() == np.identity(sf._dim)


matrix([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          T

In [79]:
a = csr_matrix((1, 5))
a[0] = 1.0
a.toarray()

/home/kensuke/Projects/Fermionic-Operator/.venv/lib/python3.10/site-packages/scipy/sparse/_index.py:146: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_arrayXarray(i, j, x)


array([[1., 1., 1., 1., 1.]])

In [64]:
a = np.array([1, 2])
a.shape

(2,)